// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApfRpx8XMcPC_xT8ILBorKRK03oJ26OwU',
    appId: '1:98511826291:web:b55c30fd8fcb2f87b32906',
    messagingSenderId: '98511826291',
    projectId: 'recipe-app-fed63',
    authDomain: 'recipe-app-fed63.firebaseapp.com',
    storageBucket: 'recipe-app-fed63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGz4gtJHbUyTUorqsNzCCY8Q8Nd_Lb-As',
    appId: '1:98511826291:android:8796c78d33c7bbfcb32906',
    messagingSenderId: '98511826291',
    projectId: 'recipe-app-fed63',
    storageBucket: 'recipe-app-fed63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPxovTrTFFQU9fOfKYkwvx3evSSKtiJj4',
    appId: '1:98511826291:ios:7bde427bb0e21464b32906',
    messagingSenderId: '98511826291',
    projectId: 'recipe-app-fed63',
    storageBucket: 'recipe-app-fed63.appspot.com',
    iosBundleId: 'com.example.dailyRecipe',
  );
}
